name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Bootstrap vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git $env:GITHUB_WORKSPACE/vcpkg
          Set-Location $env:GITHUB_WORKSPACE/vcpkg
          git checkout c27eeddba73f608f10605d80bc0144c1166f8fb7
          .\bootstrap-vcpkg.bat -disableMetrics

      - name: Configure
        shell: pwsh
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE="$env:GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake"
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        working-directory: build/Release
        run: .\veilhook_tests.exe
